config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'articles', to: 'articles#index'

  get 'articles/new', to: 'articles#new', as: :new
  post 'articles', to: 'articles#create'

  get 'articles/:id/edit', to: 'articles#edit', as: :edit
  patch 'articles/:id', to: 'articles#update'

  get 'articles/:id', to: 'articles#show', as: :article

  delete 'articles/:id', to: 'articles#destroy', as: :destroy

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.create(article_params)
    redirect_to articles_path
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    redirect_to articles_path
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<h2><%= "Edit #{@article.title}" %></h1>


<%= form_for(@article) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :content %>
  <%= f.text_field :content %>

  <%= f.submit %>
<% end %>

app/views/articles/index.html.erb
<div class="container">

<div class="d-flex space-around">
  <div class="">
    <h1 class="text-center"> Here's all your articles</h1>

      <% @articles.each do |article| %>
      <div class="border border-dark m-3 px-2 font-weight-bold shadow bg-white rounded">
        <p><%=link_to article.title, article_path(article)%></p>
        <p><%=article.content%></p>
        </p>
      </div>
      <%end%>
    </div>

  <div class="border border-dark m-3 px-2 font-weight-bold shadow bg-white rounded">
    <div class="border">
      <h3>Write new article</h3>
      <p><%= link_to "Write", new_path %></p>
      </div>
  </div>
  </div>

</div>

app/views/articles/new.html.erb
<%= form_for(@article) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :content %>
  <%= f.text_field :content %>

  <%= f.submit %>
<% end %>

app/views/articles/show.html.erb
<h1> <%= @article.title %></h1>

<h3> <%= @article.content %></h3>

<p><%= link_to "Back to articles", articles_path %></p>

<p><%= link_to "Edit this article", edit_path(@article) %></p>

<%=  link_to "Delete", destroy_path, method: :delete, data: { confirm: "Are you sure?" }%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>